version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/koing_server
permissions:
  - object: /home/ec2-user/koing_server
    owner: ec2-user
    group: ec2-user
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 60
      runas: ubuntu